force-app/main/default/objects/Prospect__c/Prospect__c.object-meta.xml
<CustomObject>
    <label>Prospect</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Prospect ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect__c/fields/Prospect_Source__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Source__c</fullName>
    <label>Prospect Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Marketing Campaign</fullName>
            </value>
            <value>
                <fullName>Cold Call</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Walk-in</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prospect__c/fields/Prospect_Status__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Status__c</fullName>
    <label>Prospect Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProspectRetrieve.cls
public class ProspectRetrieve {
    
public static void retrieveProspectRec(){
        
        Set<Id> prospectSetIds = new Set<Id>();
        
        List<Prospect__c> prospectList = [
            SELECT Id, Name, Email__c, Prospect_Source__c, Prospect_Status__c
            FROM Prospect__c
            ORDER BY Name DESC
            LIMIT 1000
        ];
        
        for(Prospect__c p : prospectList){
            prospectSetIds.add(p.Id); 
            System.debug('Prospect Name is: ' + p.Name + ', Prospect Id is: ' + p.Id + ', Prospect Email is: ' + p.Email__c + ' ,Prospect Status: ' + p.Prospect_Status__c + ' ,Prospect Source: ' + p.Prospect_Source__c);
        }
            
    }

}