force-app/main/default/objects/Prospect__c/Prospect__c.object-meta.xml
<CustomObject>
    <label>Prospect</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Prospect ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect__c/fields/Business_Development_Executive__c.field-meta.xml
<CustomField>
    <fullName>Business_Development_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Development Executive</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>BDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prospect__c/fields/Prospect_Source__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Source__c</fullName>
    <label>Prospect Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Marketing Campaign</fullName>
            </value>
            <value>
                <fullName>Cold Call</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Walk-in</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prospect__c/fields/Prospect_Status__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Status__c</fullName>
    <label>Prospect Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProspectSOSLSearch_Test.cls
@isTest
public class ProspectSOSLSearch_Test {
    
    @TestSetup
    static void testData(String searchKey){

        //create prospect records
        List<Prospect__c> prosRecs = new List<Prospect__c>();

        for(Integer i=0; i<10; i++){
            prosRecs.add(new  Prospect__c(
                Prospect_Name__c = searchKey + i,
                Email__c = searchKey + '_' + i + '@softcode.com',
                Business_Development_Executive__c = 'Victor Alabi',
                Company_Name__c = 'Softcode',
                Contact_Number__c = '+44764829062',
                Prospect_Source__c = 'Referral',
                Prospect_Status__c = ''
            ));
        }
        insert prosRecs;
        
    }
    //test method
    @isTest
    static void testProspectSOSLSearch(String searchKey){
        Test.startTest();
        ProspectSOSLSearch.handleProspectSOSLSearch();
        Test.stopTest();

        //Assert
        Assert.areEqual(expected, actual, msg)
    }
}