force-app/main/default/objects/Prospect__c/Prospect__c.object-meta.xml
<CustomObject>
    <label>Prospect</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Prospect ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prospect__c/fields/Business_Development_Executive__c.field-meta.xml
<CustomField>
    <fullName>Business_Development_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Development Executive</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>BDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prospect__c/fields/Prospect_Source__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Source__c</fullName>
    <label>Prospect Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Marketing Campaign</fullName>
            </value>
            <value>
                <fullName>Cold Call</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Walk-in</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prospect__c/fields/Prospect_Status__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Status__c</fullName>
    <label>Prospect Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProspectSOSLSearch.cls
public class ProspectSOSLSearch {
    
    public static void handleProspectSOSLSearch(String searchKey){

        List<List<Prospect__c>> searchResults = [
            FIND :searchKey
            IN all fields
            RETURNING Prospect__c(Id, Business_Development_Executive__c, 
            Company_Name__c, Contact_Number__c, 
            Email__c, Name, Prospect_Name__c, 
            Prospect_Source__c, Prospect_Status__c )];

        if(!searchResults.isEmpty()){
            List<Prospect__c> prosRecs = searchResults[0];

            if(!prosRecs.isEmpty()){
                for(Prospect__c pros : prosRecs){
                    System.debug('Prospect record fetched from SOSL search: ' + pros.Prospect_Name__c + ' ' + pros.Email__c);
                }
                
            }else {
                System.debug('No Prospect record with ' + searchKey + 'found');
            }
        }else {
            System.debug('No object record with ' + searchKey + 'found');
            }
        }
         


    }