force-app/main/default/objects/Account_Number__c/Account_Number__c.object-meta.xml
<CustomObject>
    <label>Account Number</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Number__c/fields/Account_Balance__c.field-meta.xml
<CustomField>
    <fullName>Account_Balance__c</fullName>
    <label>Account Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Number__c/fields/Account_Holder__c.field-meta.xml
<CustomField>
    <fullName>Account_Holder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Holder</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipName>Account_Holders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Number</label>
    <referenceTo>Account_Number__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account_Number__c</referenceTo>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Receiver_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Account_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver Account Number</label>
    <referenceTo>Account_Number__c</referenceTo>
    <relationshipLabel>Transactions (Receiver Account Number)</relationshipLabel>
    <relationshipName>Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BankTransfer_Queueable.cls
public class BankTransfer_Queueable implements Queueable {

    private Id transId;

    public BankTransfer_Queueable(Id t_Id) {
        this.transId = t_Id;
    }

    public void execute(QueueableContext context) {
        //fetch transaction record
        List<Transaction__c> trans = [SELECT Id, Transaction_Amount__c, Customer__c, Receiver_Account_Number__c FROM Transaction__c WHERE Id = :transId LIMIT 1];

        try {
            //fetch sender's acct balance from acct_no obj
            if (!trans.isEmpty()) {
                List<Account_Number__c> senders = [SELECT Id, Account_Holder__c, Account_Balance__c FROM Account_Number__c WHERE Account_Holder__c = :trans[0].Customer__c LIMIT 1];
                
                if (!senders.isEmpty() && trans[0].Transaction_Amount__c <= senders[0].Account_Balance__c) {
                    Account_Number__c sender = senders[0];
                    sender.Account_Balance__c -= trans[0].Transaction_Amount__c;

                    //fetch and credit receiver acct
                    List<Account_Number__c> receivers = [SELECT Id, Account_Balance__c FROM Account_Number__c WHERE Id = :trans[0].Receiver_Account_Number__c LIMIT 1];
                    
                    if (!receivers.isEmpty()) {
                        Account_Number__c receiver = receivers[0];
                        receiver.Account_Balance__c += trans[0].Transaction_Amount__c;
                        
                        //update sender and receiver acct_balance
                        update sender;
                        update receiver;
                        System.debug('Receiver successfully credited');
                    } else {
                        System.debug('Receiver account not found');
                    }
                } else {
                    System.debug('Insufficient funds or sender account not found');
                }
            } else {
                System.debug('No transaction was found with the provided Id');
            }
        } catch (Exception e) {
            System.debug('Error processing transfer: ' + e.getMessage());
            
        }
    }
}